"""add_problem_and_testcase_model

Revision ID: 3b8eac3f6172
Revises: 531ceb725337
Create Date: 2025-12-19 15:09:30.114559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8eac3f6172'
down_revision: Union[str, Sequence[str], None] = '531ceb725337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem_key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_tags', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('core_number', sa.Integer(), nullable=True),
    sa.Column('compile_command', sa.String(), nullable=True),
    sa.Column('run_command', sa.String(), nullable=False),
    sa.Column('judge_type', sa.String(), nullable=True),
    sa.Column('judge_script', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_id'), 'problem', ['id'], unique=False)
    op.create_table('test_case',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('input_path', sa.String(), nullable=False),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_id'), 'test_case', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_id'), table_name='test_case')
    op.drop_table('test_case')
    op.drop_index(op.f('ix_problem_id'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
